[0m21:04:01.565372 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094c8950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094d62d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094d6c50>]}


============================== 21:04:01.568429 | ceb256a9-b3e7-41dd-820c-55791b38a2de ==============================
[0m21:04:01.568429 [info ] [MainThread]: Running with dbt=1.7.9
[0m21:04:01.568710 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/hajung/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:04:06.008479 [debug] [MainThread]: Starter project path: /Users/hajung/anaconda3/lib/python3.11/site-packages/dbt/include/starter_project
[0m21:04:06.031036 [info ] [MainThread]: 
Your new dbt project "haebichan_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:04:06.031662 [info ] [MainThread]: Setting up your profile.
[0m21:04:06.032613 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m21:04:06.035120 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 4.4899025, "process_user_time": 0.708462, "process_kernel_time": 0.159757, "process_mem_max_rss": "104808448", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m21:04:06.035687 [debug] [MainThread]: Command `dbt init` failed at 21:04:06.035575 after 4.49 seconds
[0m21:04:06.035994 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094c20d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094c9650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104fef910>]}
[0m21:04:06.036292 [debug] [MainThread]: Flushing usage events
[0m21:15:57.702809 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10aefe010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10af0efd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10af0f450>]}


============================== 21:15:57.706145 | 18fbec9f-7b54-4b5a-a676-f1fd08ff9777 ==============================
[0m21:15:57.706145 [info ] [MainThread]: Running with dbt=1.7.9
[0m21:15:57.706414 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/hajung/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:15:57.706678 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/hajung/Desktop/experiment/dbt_snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:15:57.707898 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.026222084, "process_user_time": 0.699959, "process_kernel_time": 0.147943, "process_mem_max_rss": "105676800", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m21:15:57.708174 [debug] [MainThread]: Command `dbt run` failed at 21:15:57.708113 after 0.03 seconds
[0m21:15:57.708340 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106eccfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10aefd690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104dfb0d0>]}
[0m21:15:57.708498 [debug] [MainThread]: Flushing usage events
[0m19:34:10.741467 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104847490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061a1690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061a1000>]}


============================== 19:34:10.746197 | 94e55ce6-af00-441e-ae57-383b1499df39 ==============================
[0m19:34:10.746197 [info ] [MainThread]: Running with dbt=1.8.1
[0m19:34:10.746591 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/hajung/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:34:10.746958 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/hajung/Desktop/experiment/dbt_llm_demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:34:10.762101 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.06777871, "process_user_time": 0.697782, "process_kernel_time": 0.167675, "process_mem_max_rss": "91766784", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:34:10.762564 [debug] [MainThread]: Command `dbt run` failed at 19:34:10.762505 after 0.07 seconds
[0m19:34:10.762806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104847490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061a1330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061a02e0>]}
[0m19:34:10.763103 [debug] [MainThread]: Flushing usage events
[0m19:43:56.015034 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10718b490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109749690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109749000>]}


============================== 19:43:56.018381 | 9c879e7c-47ec-4f87-ad3f-042ede5bd3dc ==============================
[0m19:43:56.018381 [info ] [MainThread]: Running with dbt=1.8.1
[0m19:43:56.018780 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/hajung/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:43:56.019076 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/hajung/Desktop/experiment/dbt_llm_demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:43:56.019957 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.047939334, "process_user_time": 0.624451, "process_kernel_time": 0.1035, "process_mem_max_rss": "90832896", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:43:56.020302 [debug] [MainThread]: Command `dbt run` failed at 19:43:56.020249 after 0.05 seconds
[0m19:43:56.020507 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10718b490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109749330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097482e0>]}
[0m19:43:56.020689 [debug] [MainThread]: Flushing usage events
